export const sliderItems = [
  {
    _id: 1,
    image: "/images/slider/1.jpg",
  },
  {
    _id: 2,
    image: "/images/slider/2.png",
  },
  {
    _id: 3,
    image: "/images/slider/3.jpg",
  },
];

export const category = [
  {
    _id: 1,
    title: "Men",
    image: "/images/category/men.jpg",
  },
  {
    _id: 1,
    title: "Women",
    image: "/images/category/women.jpg",
  },
  {
    _id: 1,
    title: "Kids",
    image: "/images/category/kids.jpg",
  },
];

export const products = [
  {
    _id: 1,
    title: "Product 1",
    slug: "product 1",
    desc: "Description for product 1",
    category: "Men",
    image: "/images/products/1.jpg",
    image1: "/images/products/2.jpg",
    image2: "/images/products/3.jpg",
    image3: "/images/products/4.jpg",
    price: "80.00",
  },
  {
    _id: 2,
    title: "Product 2",
    slug: "product 2",
    desc: "Description for product 2",
    category: "Women",
    image: "/images/products/5.jpg",
    image1: "/images/products/6.jpg",
    image2: "/images/products/7.jpg",
    image3: "/images/products/8.jpg",
    price: "65.00",
  },
  {
    _id: 3,
    title: "Product 3",
    slug: "product 3",
    desc: "Description for product 3",
    category: "Kids",
    image: "/images/products/9.jpg",
    image1: "/images/products/10.jpg",
    image2: "/images/products/11.jpg",
    image3: "/images/products/12.jpg",
    price: "72.00",
  },
  {
    _id: 4,
    title: "Product 4",
    slug: "product 4",
    desc: "Description for product 4",
    category: "Women",
    image: "/images/products/13.jpg",
    image1: "/images/products/14.jpg",
    image2: "/images/products/15.jpg",
    image3: "/images/products/16.jpg",
    price: "92.00",
  },
  {
    _id: 5,
    title: "Product 5",
    slug: "product 5",
    desc: "Description for product 5",
    category: "Men",
    image: "/images/products/5.jpg",
    price: "99.00",
  },
  {
    _id: 6,
    title: "Product 6",
    slug: "product 6",
    desc: "Description for product 6",
    category: "Women",
    image: "/images/products/6.jpg",
    price: "88.00",
  },
  {
    _id: 7,
    title: "Product 7",
    slug: "product 7",
    desc: "Description for product 7",
    category: "Kids",
    image: "/images/products/7.jpg",
    price: "72.00",
  },
  {
    _id: 8,
    title: "Product 8",
    slug: "product 8",
    desc: "Description for product 8",
    category: "Women",
    image: "/images/products/8.jpg",
    price: "98.00",
  },
];